from turtle import *
pendown()
for n in range(2):
    left(30)
    forward(45)
    right(60)
    forward(45)
    left(60)
    forward(45)
    right(60)
    forward(45)
    left(30)
    penup()
    forward(45)
    pendown()
    left(20)
    forward(45)
    right(40)
    forward(45)
    left(20)
    penup()
    forward(45)
    pendown()
