from tkinter import *
w = Tk()
w.geometry("300x500")
w.title("вход в систему")
def reg():
    text = Label(text="для входа в систему - зарегестрируйтесь")
    text_log = Label(text="введите ваш логин")
    reg_login = Entry()
    text_password1 = label(text="введите ваш пероль")
    reg_password1 = entry()
    text_password2 = label(text="ешё раз пероль")
    reg_password2 = entry(show="*")
    btn_reg = Button(text="зарегатся!")
    text.pack()
    text_log.pack()
    reg_login.pack()
    text_password1.pack()
    reg_password1.pack()
    text_password2.pack()
    btn_reg.pack()
w.mainloop()
